### ISSUE TITLE
Gist URL for data source 404s

### ISSUE THREAD

**Issue by landondurnan** [hirokiosame/orbit-codesandbox#1]
https://github.com/privatenumber/orbit-codesandbox/blob/small-app-form/src/DataTable.vue#L104

fetch request: https://gist.githubusercontent.com/hirokiosame/ should be https://gist.githubusercontent.com/privatenumber/

**Comment by privatenumber** [comment]
Fixed https://github.com/privatenumber/orbit-codesandbox/commit/54094db8a6b6545367749cb796b3aab55d9bebc0
